require "marcman/version"

module Marcman
  # [description, is repeatable?]
  MARC = {
    "001" => ["Control Number", false],
    "003" => ["Control Number Identifier", false],
    "005" => ["Date and Time of Latest Transaction", false],
    "006" => [
      "Fixed-Length Data Elements - Additional Material Characteristics",
      false
    ],
    "007" => ["Physical Description Fixed Field", false],
    "008" => ["Fixed-Length Data Elements", false],
    "010" => ["Library of Congress Control Number", false],
    "013" => ["Patent Control Information", true],
    "015" => ["National Bibliography Number", true],
    "016" => ["National Bibliographic Agency Control Number", true],
    "017" => ["Copyright or Legal Deposit Number", true],
    "018" => ["Copyright Article-Fee Code", false],
    "020" => ["International Standard Book Number", true],
    "022" => ["International Standard Serial Number", true],
    "024" => ["Other Standard Identifier", true],
    "025" => ["Overseas Acquisition Number", true],
    "026" => ["Fingerprint Identifier", true],
    "027" => ["Standard Technical Report Number", true],
    "028" => ["Publisher or Distributor Number", true],
    "030" => ["CODEN Designation", true],
    "031" => ["Musical Incipits Information", true],
    "032" => ["Postal Registration Number", true],
    "033" => ["Date/Time and Place of an Event", true],
    "034" => ["Coded Cartographic Mathematical Data", true],
    "035" => ["System Control Number", true],
    "036" => ["Original Study Number for Computer Data Files", false],
    "037" => ["Source of Acquisition", true],
    "038" => ["Record Content Licensor", false],
    "040" => ["Cataloging Source", false],
    "041" => ["Language Code", true],
    "042" => ["Authentication Code", false],
    "043" => ["Geographic Area Code", false],
    "044" => ["Country of Publishing/Producing Entity Code", false],
    "045" => ["Time Period of Content", false],
    "046" => ["Special Coded Dates", true],
    "047" => ["Form of Musical Composition Code", true],
    "048" => ["Number of Musical Instruments or Voices Codes", true],
    "050" => ["Library of Congress Call Number", true],
    "051" => ["Library of Congress Copy, Issue, Offprint Statement", true],
    "052" => ["Geographic Classification", true],
    "055" => ["Classification Numbers Assigned in Canada", true],
    "060" => ["National Library of Medicine Call Number", true],
    "061" => ["National Library of Medicine Copy Statement", true],
    "066" => ["Character Sets Present", false],
    "070" => ["National Agricultural Library Call Number", true],
    "071" => ["National Agricultural Library Copy Statement", true],
    "072" => ["Subject Category Code", true],
    "074" => ["GPO Item Number", true],
    "080" => ["Universal Decimal Classification Number", true],
    "082" => ["Dewey Decimal Classification Number", true],
    "083" => ["Additional Dewey Decimal Classification Number", true],
    "084" => ["Other Classification Number", true],
    "085" => ["Synthesized Classification Number Components", true],
    "086" => ["Government Document Classification Number", true],
    "088" => ["Report Number", true],
    "09X" => ["Local Call Numbers"],
    "100" => ["Main Entry - Personal Name", false],
    "110" => ["Main Entry - Corporate Name", false],
    "111" => ["Main Entry - Meeting Name", false],
    "130" => ["Main Entry - Uniform Title", false],
    "210" => ["Abbreviated Title", true],
    "222" => ["Key Title", true],
    "240" => ["Uniform Title", false],
    "242" => ["Translation of Title by Cataloging Agency", true],
    "243" => ["Collective Uniform Title", false],
    "245" => ["Title Statement", false],
    "246" => ["Varying Form of Title", true],
    "247" => ["Former Title", true],
    "250" => ["Edition Statement", true],
    "254" => ["Musical Presentation Statement", false],
    "255" => ["Cartographic Mathematical Data", true],
    "256" => ["Computer File Characteristics", false],
    "257" => ["Country of Producing Entity", true],
    "258" => ["Philatelic Issue Data", true],
    "260" => ["Publication, Distribution, etc. (Imprint)", true],
    "263" => ["Projected Publication Date", false],
    "264" => ["Production, Publication, Distribution, Manufacture, and Copyright Notice", true],
    "270" => ["Address", true],
    "300" => ["Physical Description", true],
    "306" => ["Playing Time", false],
    "307" => ["Hours, etc.", true],
    "310" => ["Current Publication Frequency", false],
    "321" => ["Former Publication Frequency", true],
    "336" => ["Content Type", true],
    "337" => ["Media Type", true],
    "338" => ["Carrier Type", true],
    "340" => ["Physical Medium", true],
    "342" => ["Geospatial Reference Data", true],
    "343" => ["Planar Coordinate Data", true],
    "344" => ["Sound Characteristics", true],
    "345" => ["Projection Characteristics of Moving Image", true],
    "346" => ["Video Characteristics", true],
    "347" => ["Digital File Characteristics", true],
    "348" => ["Format of Notated Music", true],
    "351" => ["Organization and Arrangement of Materials", true],
    "352" => ["Digital Graphic Representation", true],
    "355" => ["Security Classification Control", true],
    "357" => ["Originator Dissemination Control", false],
    "362" => ["Dates of Publication and/or Sequential Designation", true],
    "363" => ["Normalized Date and Sequential Designation", true],
    "365" => ["Trade Price", true],
    "366" => ["Trade Availability Information", true],
    "370" => ["Associated Place", true],
    "377" => ["Associated Language", true],
    "380" => ["Form of Work", true],
    "381" => [
      "Other Distinguishing Characteristics of Work or Expression",
      true
    ],
    "382" => ["Medium of Performance", true],
    "383" => ["Numeric Designation of Musical Work", true],
    "384" => ["Key", false],
    "385" => ["Audience Characteristics", true],
    "386" => ["Creator/Contributor Characteristics", true],
    "388" => ["Time Period of Creation", true],
    "490" => ["Series Statement", true],
    "500" => ["General Note", true],
    "501" => ["With Note", true],
    "502" => ["Dissertation Note", true],
    "504" => ["Bibliography, etc. Note", true],
    "505" => ["Formatted Contents Note", true],
    "506" => ["Restrictions on Access Note", true],
    "507" => ["Scale Note for Graphic Material", false],
    "508" => ["Creation/Production Credits Note", true],
    "510" => ["Citation/References Note", true],
    "511" => ["Participant or Performer Note", true],
    "513" => ["Type of Report and Period Covered Note", true],
    "514" => ["Data Quality Note", false],
    "515" => ["Numbering Peculiarities Note", true],
    "516" => ["Type of Computer File or Data Note", true],
    "518" => ["Date/Time and Place of an Event Note", true],
    "520" => ["Summary, etc.", true],
    "521" => ["Target Audience Note", true],
    "522" => ["Geographic Coverage Note", true],
    "524" => ["Preferred Citation of Described Materials Note", true],
    "525" => ["Supplement Note", true],
    "526" => ["Study Program Information Note", true],
    "530" => ["Additional Physical Form available Note", true],
    "533" => ["Reproduction Note", true],
    "534" => ["Original Version Note", true],
    "535" => ["Location of Originals/Duplicates Note", true],
    "536" => ["Funding Information Note", true],
    "538" => ["System Details Note", true],
    "540" => ["Terms Governing Use and Reproduction Note", true],
    "541" => ["Immediate Source of Acquisition Note", true],
    "542" => ["Information Relating to Copyright Status", true],
    "544" => ["Location of Other Archival Materials Note", true],
    "545" => ["Biographical or Historical Data", true],
    "546" => ["Language Note", true],
    "547" => ["Former Title Complexity Note", true],
    "550" => ["Issuing Body Note", true],
    "552" => ["Entity and Attribute Information Note", true],
    "555" => ["Cumulative Index/Finding Aids Note", true],
    "556" => ["Information About Documentation Note", true],
    "561" => ["Ownership and Custodial History", true],
    "562" => ["Copy and Version Identification Note", true],
    "563" => ["Binding Information", true],
    "565" => ["Case File Characteristics Note", true],
    "567" => ["Methodology Note", true],
    "580" => ["Linking Entry Complexity Note", true],
    "581" => ["Publications About Described Materials Note", true],
    "583" => ["Action Note", true],
    "584" => ["Accumulation and Frequency of Use Note", true],
    "585" => ["Exhibitions Note", true],
    "586" => ["Awards Note", true],
    "588" => ["Source of Description Note", true],
    "59X" => ["Local Notes"],
    "600" => ["Subject Added Entry - Personal Name", true],
    "610" => ["Subject Added Entry - Corporate Name", true],
    "611" => ["Subject Added Entry - Meeting Name", true],
    "630" => ["Subject Added Entry - Uniform Title", true],
    "647" => ["Subject Added Entry - Named Event", true],
    "648" => ["Subject Added Entry - Chronological Term", true],
    "650" => ["Subject Added Entry - Topical Term", true],
    "651" => ["Subject Added Entry - Geographic Name", true],
    "653" => ["Index Term - Uncontrolled", true],
    "654" => ["Subject Added Entry - Faceted Topical Terms", true],
    "655" => ["Index Term - Genre/Form", true],
    "656" => ["Index Term - Occupation", true],
    "657" => ["Index Term - Function", true],
    "658" => ["Index Term - Curriculum Objective", true],
    "662" => ["Subject Added Entry - Hierarchical Place Name", true],
    "69X" => ["Local Subject Access Fields", true],
    "700" => ["Added Entry - Personal Name", true],
    "710" => ["Added Entry - Corporate Name", true],
    "711" => ["Added Entry - Meeting Name", true],
    "720" => ["Added Entry - Uncontrolled Name", true],
    "730" => ["Added Entry - Uniform Title", true],
    "740" => ["Added Entry - Uncontrolled Related/Analytical Title", true],
    "751" => ["Added Entry - Geographic Name", true],
    "752" => ["Added Entry - Hierarchical Place Name", true],
    "753" => ["System Details Access to Computer Files", true],
    "754" => ["Added Entry - Taxonomic Identification", true],
    "758" => ["Resource Identifier", true],
    "760" => ["Main Series Entry", true],
    "762" => ["Subseries Entry", true],
    "765" => ["Original Language Entry", true],
    "767" => ["Translation Entry", true],
    "770" => ["Supplement/Special Issue Entry", true],
    "772" => ["Supplement Parent Entry", true],
    "773" => ["Host Item Entry", true],
    "774" => ["Constituent Unit Entry", true],
    "775" => ["Other Edition Entry", true],
    "776" => ["Additional Physical Form Entry", true],
    "777" => ["Issued With Entry", true],
    "780" => ["Preceding Entry", true],
    "785" => ["Succeeding Entry", true],
    "786" => ["Data Source Entry", true],
    "787" => ["Other Relationship Entry", true],
    "800" => ["Series Added Entry - Personal Name", true],
    "810" => ["Series Added Entry - Corporate Name", true],
    "811" => ["Series Added Entry - Meeting Name", true],
    "830" => ["Series Added Entry - Uniform Title", true],
    "841" => ["Holdings Coded Data Values", false],
    "842" => ["Textual Physical Form Designator", false],
    "843" => ["Reproduction Note", true],
    "844" => ["Name of Unit", false],
    "845" => ["Terms Governing Use and Reproduction", true],
    "850" => ["Holding Institution", true],
    "852" => ["Location", true],
    "853" => ["Captions and Pattern - Basic Bibliographic Unit", true],
    "854" => ["Captions and Pattern - Supplementary Material", true],
    "855" => ["Captions and Pattern - Indexes", true],
    "856" => ["Electronic Location and Access", true],
    "863" => ["Enumeration and Chronology - Basic Bibliographic Unit", true],
    "864" => ["Enumeration and Chronology - Supplementary Material", true],
    "865" => ["Enumeration and Chronology - Indexes", true],
    "866" => ["Textual Holdings - Basic Bibliographic Unit", true],
    "867" => ["Textual Holdings - Supplementary Material", true],
    "868" => ["Textual Holdings - Indexes", true],
    "876" => ["Item Information - Basic Bibliographic Unit", true],
    "877" => ["Item Information - Supplementary Material", true],
    "878" => ["Item Information - Indexes", true],
    "880" => ["Alternate Graphic Representation", true],
    "882" => ["Replacement Record Information", false],
    "883" => ["Machine-generated Metadata Provenance", true],
    "884" => ["Description Conversion Information", true],
    "885" => ["Matching Information", true],
    "886" => ["Foreign MARC Information Field", true],
    "887" => ["Non-MARC Information Field", true],
  }

  INDICATORS = {
    "010" => [:undefined, :undefined],
    "013" => [:undefined, :undefined],
    "015" => [:undefined, :undefined],
    "016" => [
      {:definition => "National bibliographic agency",
       :values => {"#" => "Library and Archives Canada",
                   "7" => "Source specified in subfield $2"},
      },
      :undefined],
    "017" => [
      :undefined,
      {:definition => "Display constant controller",
       :values => {"#" => "Copyright or legal deposit number",
                   "8" => "No display constant generated"},
      }],
    "018" => [:undefined, :undefined],
    "020" => [:undefined, :undefined],
    "022" => [
      {:definition => "Level of international interest",
       :values => {"#" => "No level specified",
                   "1" => "Continuing resource of international interest",
                   "2" => "Continuing resource not of international interest"},
      },
      :undefined],
    "024" => [
      {:definition => "Type of standard number or code",
       :values => {"0" => "International Standard Recording Code",
                   "1" => "Universal Product Code",
                   "2" => "International Standard Music Number",
                   "3" => "International Article Number",
                   "4" => "Serial Item and Contribution Identifier",
                   "7" => "Source specified in subfield $2",
                   "8" => "Unspecified type of standard number or code"}
      },
      {:definition => "Difference indicator",
       :values => {"#" => "No information provided",
                   "0" => "No difference",
                   "1" => "Difference"}
      }],
    "025" => [:undefined, :undefined],
    "026" => [:undefined, :undefined],
    "027" => [:undefined, :undefined],
    "028" => [
      {:definition => "Type of number",
       :values => {"0" => "Issue number",
                   "1" => "Matrix number",
                   "2" => "Plate number",
                   "3" => "Other music publisher number",
                   "4" => "Video recording publisher number",
                   "5" => "Other publisher number",
                   "6" => "Distributor number"}
      },
      {:definition => "Note/added entry controller",
       :values => {"0" => "No note, no added entry",
                   "1" => "Note, added entry",
                   "2" => "Note, no added entry",
                   "3" => "No note, added entry"}
      }],
    "030" => [:undefined, :undefined],
    "031" => [:undefined, :undefined],
    "032" => [:undefined, :undefined],
    "033" => [
      {:definition => "Type of date in subfield $a",
       :values => {"#" => "No date information",
                   "0" => "Single date",
                   "1" => "Multiple single dates",
                   "2" => "Range of dates"}
      },
      {:definition => "Type of event",
       :values => {"#" => "No information provided",
                   "0" => "Capture",
                   "1" => "Broadcast",
                   "2" => "Finding"}
      },
    ],
    "034" => [
      {:definition => "Type of scale",
       :values => {"0" => "Scale indeterminable/No scale recorded",
                   "1" => "Single scale",
                   "3" => "Range of scales"}
      },
      {:definition => "Type of ring",
       :values => {"#" => "Not applicable",
                   "0" => "Outer ring",
                   "1" => "Exclusion ring"}
      }
    ],
    "035" => [:undefined, :undefined],
    "036" => [:undefined, :undefined],
    "037" => [
      {:definition => "Source of acquisition sequence",
       :values => {"#" => "Not applicable/No information provided/Earliest",
                   "2" => "Intervening",
                   "3" => "Current/Latest"}
      },
      :undefined
    ],
    "038" => [:undefined, :undefined],
    "040" => [:undefined, :undefined],
    "041" => [
      {:definition => "Translation indication",
       :values => {"#" => "No information provided",
                   "0" =>
                   "Item not a translation/does not include a translation",
                   "1" => "Item is or includes a translation"}
      },
      {:definition => "Source of code",
       :values => {"#" => "MARC language code",
                   "7" => "Source specified in subfield $2"}
      }
    ],
    "042" => [:undefined, :undefined],
    "043" => [:undefined, :undefined],
    "044" => [:undefined, :undefined],
    "045" => [
      {:definition => "Type of time period in subfield $b or $c",
       :values => {"#" => "Subfield $b or $c not present",
                   "0" => "Single date/time",
                   "1" => "Multiple single dates/times",
                   "2" => "Range of dates/times"}
      },
      :undefined
    ],
    "046" => [:undefined, :undefined],
    "047" => [
      :undefined,
      {:description => "Source of code",
       :values => {"#" => "MARC musical composition code",
                   "7" => "Source specified in subfield $2"}
      }
    ],
    "048" => [
      :undefined,
      {:description => "Source of code",
       :values => {"#" => "MARC code",
                   "7" => "Source specified in subfield $2"}
      }
    ],
    "050" => [
      {:description => "Existence in LC collection",
       :values => {"#" => "No information provided",
                   "0" => "Item is in LC",
                   "1" => "Item is not in LC"}
      },
      {:description => "Source of call number",
       :values => {"0" => "Assigned by LC",
                   "4" => "Assigned by agency other than LC"}
      }
    ],
    "051" => [:undefined, :undefined],
    "052" => [
      {:description => "Code source",
       :values => {"#" => "Library of Congress Classification",
                   "1" => "U.S. Dept. of Defense Classification",
                   "7" => "Source specified in subfield $2"}
      },
      :undefined
    ],
    "055" => [
      {:description => "Existence in LAC collection",
       :values => {"#" => "Information not provided",
                   "0" => "Work held by LAC",
                   "1" => "Work not held by LAC"}
      },
      {:description => "Type, completeness, source of class/call number",
       :values => {"0" => "LC-based call number assigned by LAC",
                   "1" => "Complete LC class number assigned by LAC",
                   "2" => "Incomplete LC class number assigned by LAC",
                   "3" => "LC-based call number assigned by the contributing library",
                   "4" => "Complete LC class number assigned by the contributing library",
                   "5" => "Incomplete LC class number assigned by the contributing library",
                   "6" => "Other call number assigned by LAC",
                   "7" => "Other class number assigned by LAC",
                   "8" => "Other call number assigned by the contributing library",
                   "9" => "Other class number assigned by the contributing library"}
      }
    ],
    "060" => [
      {:description => "Existence in NLM collection",
       :values => {"#" => "Information not provided",
                   "0" => "Item is in NLM",
                   "1" => "Item is not in NLM"}
      },
      {:description => "Source of call number",
       :values => {"0" => "Assigned by NLM",
                   "4" => "Assigned by agency other than NLM"}
      }
    ],
    "061" => [:undefined, :undefined],
    "066" => [:undefined, :undefined],
    "070" => [
      {:description => "Existence in NAL collection",
       :values => {"#" => "Information not provided",
                   "0" => "Item is in NAL",
                   "1" => "Item is not in NAL"}
      },
      :undefined],
    "071" => [:undefined, :undefined],
    "072" => [
      :undefined,
      {:description => "Code source",
       :values => {"0" => "NAL subject category code list",
                   "7" => "Source specified in subfield $2"}
      }
    ],
    "074" => [:undefined, :undefined],
    "080" => [
      {:definition => "Type of edition",
       :values => {"#" => "No information provided",
                   "0" => "Full",
                   "1" => "Abridged"}
      },
      :undefined],
    "082" => [
      {:definition => "Type of edition",
       :values => {"0" => "Full edition",
                   "1" => "Abridged edition",
                   "7" => "Other edition specified in subfield $2"}
      },
      {:description => "Source of classification number",
       :values => {"0" => "Assigned by LC",
                   "4" => "Assigned by agency other than LC"}
      }
    ],
    "083" => [
      {:definition => "Type of edition",
       :values => {"0" => "Full edition",
                   "1" => "Abridged edition",
                   "7" => "Other edition specified in subfield $2"}
      },
      :undefined],
    "084" => [:undefined, :undefined],
    "085" => [:undefined, :undefined],
    "086" => [
      {:definition => "Number source",
       :values => {
         "#" => "Source specified in subfield $2",
         "0" => "Superintendent of Documents Classification System",
         "1" => "Government of Canada Publications: Outline of Classification"}
      },
      :undefined
    ],
    "088" => [:undefined, :undefined],
    "09X" => [:undefined, :undefined],
  }

  def self.formatIndicators(code, ind)
    label = ind == 1 ? "first" : "second"
    indicator = INDICATORS[code][ind -1]
    if indicator == :undefined
      return ["  %s indicator is undefined" % label]
    end

    return ["  %s indicator: %s" % [label, indicator[:definition]]] +
           indicator[:values].map{|k, v| "    %s - %s" % [k, v]}
  end
    
end
