#!/usr/bin/env ruby

require "launchy"
require "marcman"


options = {:browser => false,
           :indicators => false,
           :repeat=>false,
           :subfields => false}

OptionParser.new do |opts|
  opts.banner = "Usage: marcman [CODE] [options]"

  opts.on("-i", "--[no-]indicators", "Show indicator definitions") do |i|
    options[:indicators] = i
  end

  opts.on("-s", "--[no-]subfields", "Show subfield definitions") do |s|
    options[:subfields] = s
  end

  opts.on("-r", "--[no-]repeatable",
          "Show repeatability of fields and subfields") do |r|
    options[:repeat] = r
  end

  opts.on("-b", "--[no-]browse", "Open in browser") do |b|
    options[:browser] = b
  end

end.parse!

code = ARGV.first.upcase
unless code =~ /[0-9X]{3}/
  puts "I don't recognize \"%s\". Please enter a 3-character MARC field code." %
       code
  exit 1
end

field = Marcman::CODES[code]

if field.nil?
  puts "No MARC field with the code %s" % code
  exit 0
end

#desc, repeat = field

puts "%s: %s%s" % [code, field[:definition], Marcman::formatRepeat(field[:repeat], options[:repeat])]
if options[:indicators] and Marcman::CODES[code][:indicators]
  (1..2).each do |i|
    puts Marcman::formatIndicators(code, i).join("\n")
  end
end

if options[:subfields] and Marcman::CODES[code][:subfields]
  puts "  Subfields:"
  puts Marcman::formatSubfields(code, options[:repeat]).join("\n")
end

if options[:browser]
  if Marcman::CODES[code][:docurl].nil?
    Launchy.open(
      "https://www.loc.gov/marc/bibliographic/bd%s.html" % code.downcase
    )
  else
    Launchy.open(Marcman::CODES[code][:docurl])
  end
end
